<?xml version="1.0" encoding="utf-8"?><Database Name="Connet" Class="ConnetDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Connet.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnetConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Address" Member="Addresses">
    <Type Name="Address">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AddressLine" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Zipcode" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="User_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Address_Order" Member="Orders" ThisKey="Id" OtherKey="Address_Id" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Stream_Product" Member="Stream_Products">
    <Type Name="Stream_Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomID" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Stream_Product" Member="Product" ThisKey="ProductID" OtherKey="Id" Type="Product" IsForeignKey="true" />
      <Association Name="Stream_Stream_Product" Member="Stream" ThisKey="RoomID" OtherKey="Id" Type="Stream" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(44) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Buyer" Member="Buyers">
    <Type Name="Buyer">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(44) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateJoined" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Buyer_Cart" Member="Carts" ThisKey="Id" OtherKey="Buyer_Id" Type="Cart" />
      <Association Name="Buyer_Order" Member="Orders" ThisKey="Id" OtherKey="Buyer_Id" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Cart" Member="Carts">
    <Type Name="Cart">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Buyer_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Buyer_Cart" Member="Buyer" ThisKey="Buyer_Id" OtherKey="Id" Type="Buyer" IsForeignKey="true" />
      <Association Name="Product_Cart" Member="Product" ThisKey="Product_Id" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Order_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Order_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="Buyer_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Address_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_Order_Detail" Member="Order_Details" ThisKey="Id" OtherKey="Order_Id" Type="Order_Detail" />
      <Association Name="Address_Order" Member="Address" ThisKey="Address_Id" OtherKey="Id" Type="Address" IsForeignKey="true" />
      <Association Name="Buyer_Order" Member="Buyer" ThisKey="Buyer_Id" OtherKey="Id" Type="Buyer" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Order_Detail" Member="Order_Details">
    <Type Name="Order_Detail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Order_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Association Name="Order_Order_Detail" Member="Order" ThisKey="Order_Id" OtherKey="Id" Type="Order" IsForeignKey="true" />
      <Association Name="Product_Order_Detail" Member="Product" ThisKey="Product_Id" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Seller_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Stream_Product" Member="Stream_Products" ThisKey="Id" OtherKey="ProductID" Type="Stream_Product" />
      <Association Name="Product_Cart" Member="Carts" ThisKey="Id" OtherKey="Product_Id" Type="Cart" />
      <Association Name="Product_Order_Detail" Member="Order_Details" ThisKey="Id" OtherKey="Product_Id" Type="Order_Detail" />
      <Association Name="Seller_Product" Member="Seller" ThisKey="Seller_Id" OtherKey="Id" Type="Seller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Seller" Member="Sellers">
    <Type Name="Seller">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateJoined" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Seller_Product" Member="Products" ThisKey="Id" OtherKey="Seller_Id" Type="Product" />
      <Association Name="Seller_Stream" Member="Streams" ThisKey="Id" OtherKey="Seller_Id" Type="Stream" />
    </Type>
  </Table>
  <Table Name="dbo.OrderSales" Member="OrderSales">
    <Type Name="OrderSale">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="SellerName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Verified" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateJoined" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Stream" Member="Streams">
    <Type Name="Stream">
      <Column Name="Id" Type="System.String" DbType="VarChar(36) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TotalView" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Seller_Id" Type="System.String" DbType="VarChar(36) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Screenshot" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Stream_Stream_Product" Member="Stream_Products" ThisKey="Id" OtherKey="RoomID" Type="Stream_Product" />
      <Association Name="Seller_Stream" Member="Seller" ThisKey="Seller_Id" OtherKey="Id" Type="Seller" IsForeignKey="true" />
    </Type>
  </Table>
</Database>